Remove QNN tests from CI suites (#1350)
Remove all QNN hardware tests from the test suites.

---------

Signed-off-by: Rishin Raj <rishinr@qti.qualcomm.com>

diff --git a/scripts/Jenkinsfile b/scripts/Jenkinsfile
--- a/scripts/Jenkinsfile
+++ b/scripts/Jenkinsfile
@@ -405,7 +405,6 @@ pipeline {
                                     export TOKENIZERS_PARALLELISM=false &&
                                     export QEFF_HOME=/efficient-transformers/Non_cli_qaic &&
                                     python -m pytest tests -m '(not reproducer) and (not on_qaic) and (not dynamo) and (not weight_free) and (not finetune) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline -n 4 -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=export_compile --junitxml=tests/tests_log1.xml --durations=10 &&
-                                    junitparser merge tests/tests_log1.xml tests/tests_log.xml &&
                                     deactivate"
                                     '''
                                 }
@@ -427,8 +426,7 @@ pipeline {
                                     export TOKENIZERS_PARALLELISM=false &&
                                     export QEFF_ISOLATE_QAIC_WORKERS=1 &&
                                     export QEFF_HOME=/efficient-transformers/Non_qaic_llm &&
-                                    python -m pytest tests -m '(not reproducer) and (llm_model) and (not dynamo) and (not weight_free) and (not qnn) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' -k 'not test_per_pr_causal_bf16_subfunction_cb_ccl_compile_only' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline -n ${CI_QAIC_WORKERS} -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_llm --junitxml=tests/tests_log2.xml --durations=10 &&
-                                    junitparser merge tests/tests_log2.xml tests/tests_log.xml &&
+                                    python -m pytest tests -m '(not reproducer) and (llm_model) and (not dynamo) and (not weight_free) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' -k 'not test_per_pr_causal_bf16_subfunction_cb_ccl_compile_only' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline -n ${CI_QAIC_WORKERS} -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_llm --junitxml=tests/tests_log2.xml --durations=10 &&
                                     deactivate"
                                     '''
                                 }
@@ -448,8 +446,8 @@ pipeline {
                             sudo docker exec -e QEFF_MODEL_TIER=${MODEL_TIER} -e TMPDIR=/efficient-transformers/.ci-tmp/qaic_feature ${BUILD_TAG} bash -c "
                             cd /efficient-transformers && . preflight_qeff/bin/activate && mkdir -p /efficient-transformers/Non_qaic_feature &&
                             export TOKENIZERS_PARALLELISM=false && export QEFF_ISOLATE_QAIC_WORKERS=1 && export QEFF_HOME=/efficient-transformers/Non_qaic_feature &&
-                            python -m pytest tests -m '(not reproducer) and (on_qaic) and (feature) and (not multimodal) and (not qnn) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/transformers/sampler --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline -n ${CI_QAIC_WORKERS} -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_feature --junitxml=tests/tests_log2_feature.xml --durations=10 &&
-                            junitparser merge tests/tests_log2_feature.xml tests/tests_log.xml && deactivate"
+                            python -m pytest tests -m '(not reproducer) and (on_qaic) and (feature) and (not multimodal) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/transformers/sampler --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline -n ${CI_QAIC_WORKERS} -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_feature --junitxml=tests/tests_log2_feature.xml --durations=10 &&
+                            deactivate"
                             '''
                         }
                     }
@@ -466,8 +464,8 @@ pipeline {
                             sudo docker exec -e QEFF_MODEL_TIER=${MODEL_TIER} -e TMPDIR=/efficient-transformers/.ci-tmp/qaic_embedding_audio ${BUILD_TAG} bash -c "
                             cd /efficient-transformers && . preflight_qeff/bin/activate && mkdir -p /efficient-transformers/Non_qaic_embedding_audio &&
                             export TOKENIZERS_PARALLELISM=false && export QEFF_ISOLATE_QAIC_WORKERS=1 && export QEFF_HOME=/efficient-transformers/Non_qaic_embedding_audio &&
-                            python -m pytest tests -m '(not reproducer) and (embedding_audio_model) and (not qnn) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_feature --junitxml=tests/tests_log_embedding_audio.xml --durations=10 &&
-                            junitparser merge tests/tests_log_embedding_audio.xml tests/tests_log.xml && deactivate"
+                            python -m pytest tests -m '(not reproducer) and (embedding_audio_model) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_feature --junitxml=tests/tests_log_embedding_audio.xml --durations=10 &&
+                            deactivate"
                             '''
                         }
                     }
@@ -487,13 +485,10 @@ pipeline {
                                 export TOKENIZERS_PARALLELISM=false && export QEFF_HOME=/efficient-transformers/Non_cli_qaic_multimodal &&
                                 rm -f tests/tests_log6.xml &&
                                 if [ -r /opt/qti-aic/versions/apps.xml ]; then echo 'QAIC Apps SDK version:'; cat /opt/qti-aic/versions/apps.xml; fi;
-                                python -m pytest tests -m '(not reproducer) and (multimodal) and (not qnn) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline --ignore tests/transformers/models/reranker/test_reranker_mad.py -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_multimodal --junitxml=tests/tests_log6.xml --durations=10;
+                                python -m pytest tests -m '(not reproducer) and (multimodal) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline --ignore tests/transformers/models/reranker/test_reranker_mad.py -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_multimodal --junitxml=tests/tests_log6.xml --durations=10;
                                 test_status=\\$?;
-                                junitparser merge tests/tests_log6.xml tests/tests_log.xml;
-                                merge_status=\\$?;
                                 deactivate;
-                                if [ \"\\$test_status\" -ne 0 ]; then exit \"\\$test_status\"; fi;
-                                exit \"\\$merge_status\""
+                                if [ \"\\$test_status\" -ne 0 ]; then exit \"\\$test_status\"; fi"
                                 '''
                             }
                         } else {
@@ -502,9 +497,20 @@ pipeline {
                                 sudo docker exec -e QEFF_MODEL_TIER=${MODEL_TIER} -e TMPDIR=/efficient-transformers/.ci-tmp/qaic_multimodal ${BUILD_TAG} bash -c "
                                 cd /efficient-transformers && . preflight_qeff/bin/activate &&
                                 rm -rf /efficient-transformers/Non_cli_qaic_multimodal && mkdir -p /efficient-transformers/Non_cli_qaic_multimodal &&
+                                rm -f tests/tests_log6.xml tests/tests_log6_warm.xml &&
                                 export TOKENIZERS_PARALLELISM=false && export QEFF_HOME=/efficient-transformers/Non_cli_qaic_multimodal &&
                                 export QEFF_PER_PR_COMPILE_WARM_ONLY=1 &&
-                                python -m pytest tests -m '(not reproducer) and (multimodal) and (not qnn) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline --ignore tests/transformers/models/reranker/test_reranker_mad.py -n ${MM_COMPILE_N} --dist worksteal -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_multimodal --durations=10 &&
+                                python -m pytest tests -m '(not reproducer) and (multimodal) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline --ignore tests/transformers/models/reranker/test_reranker_mad.py -n ${MM_COMPILE_N} --dist worksteal -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_multimodal --junitxml=tests/tests_log6_warm.xml --durations=10;
+                                test_status=\\$?;
+                                if [ \"\\$test_status\" -ne 0 ]; then
+                                  if [ -f tests/tests_log6_warm.xml ]; then
+                                    cp tests/tests_log6_warm.xml tests/tests_log6.xml;
+                                    rm -f tests/tests_log6_warm.xml;
+                                  fi;
+                                  deactivate;
+                                  exit \"\\$test_status\";
+                                fi;
+                                rm -f tests/tests_log6_warm.xml;
                                 deactivate"
                                 '''
                             }
@@ -516,13 +522,10 @@ pipeline {
                                 export QEFF_PER_PR_SHARED_HOME=1 &&
                                 rm -f tests/tests_log6.xml &&
                                 if [ -r /opt/qti-aic/versions/apps.xml ]; then echo 'QAIC Apps SDK version:'; cat /opt/qti-aic/versions/apps.xml; fi;
-                                python -m pytest tests -m '(not reproducer) and (multimodal) and (not qnn) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline --ignore tests/transformers/models/reranker/test_reranker_mad.py -n ${MM_EXEC_N} --dist worksteal -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_multimodal --junitxml=tests/tests_log6.xml --durations=10;
+                                python -m pytest tests -m '(not reproducer) and (multimodal) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline --ignore tests/transformers/models/reranker/test_reranker_mad.py -n ${MM_EXEC_N} --dist worksteal -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_multimodal --junitxml=tests/tests_log6.xml --durations=10;
                                 test_status=\\$?;
-                                junitparser merge tests/tests_log6.xml tests/tests_log.xml;
-                                merge_status=\\$?;
                                 deactivate;
-                                if [ \"\\$test_status\" -ne 0 ]; then exit \"\\$test_status\"; fi;
-                                exit \"\\$merge_status\""
+                                if [ \"\\$test_status\" -ne 0 ]; then exit \"\\$test_status\"; fi"
                                 '''
                             }
                         }
@@ -564,7 +567,6 @@ pipeline {
                               junitparser merge tests/tests_log_disagg_batch_*.xml tests/tests_log_disagg.xml &&
                               if [ "${exit_status:-0}" -ne 0 ]; then exit "$exit_status"; fi
                             fi &&
-                            junitparser merge tests/tests_log_disagg.xml tests/tests_log.xml &&
                             deactivate
                             '
                             '''
@@ -583,7 +585,7 @@ pipeline {
                             cd /efficient-transformers && . preflight_qeff/bin/activate && mkdir -p /efficient-transformers/Non_cli_qaic_reranker &&
                             export TOKENIZERS_PARALLELISM=false && export QEFF_ISOLATE_QAIC_WORKERS=1 && export QEFF_HOME=/efficient-transformers/Non_cli_qaic_reranker && export QEFF_RERANKER_DOC_LIMIT=1 &&
                             python -m pytest -q tests/transformers/models/reranker/test_reranker_mad.py --maxfail=1 -n ${CI_QAIC_WORKERS} -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_reranker --junitxml=tests/tests_log_reranker.xml --durations=10 &&
-                            junitparser merge tests/tests_log_reranker.xml tests/tests_log.xml && deactivate"
+                            deactivate"
                             '''
                         }
                     }
@@ -601,7 +603,7 @@ pipeline {
                             cd /efficient-transformers && . preflight_qeff/bin/activate && mkdir -p /efficient-transformers/Non_cli_qaic_diffusion &&
                             export TOKENIZERS_PARALLELISM=false && export QEFF_ISOLATE_QAIC_WORKERS=1 && export QEFF_HOME=/efficient-transformers/Non_cli_qaic_diffusion && export HF_HUB_CACHE=/huggingface_hub &&
                             python -m pytest tests -m 'diffusion_models and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline -n ${CI_QAIC_WORKERS} -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=qaic_diffusion --junitxml=tests/tests_log_diffusion.xml --durations=10 &&
-                            junitparser merge tests/tests_log_diffusion.xml tests/tests_log.xml && deactivate"
+                            deactivate"
                             '''
                         }
                     }
@@ -618,8 +620,8 @@ pipeline {
                             sudo docker exec -e QEFF_MODEL_TIER=${MODEL_TIER} -e TMPDIR=/efficient-transformers/.ci-tmp/cli ${BUILD_TAG} bash -c "
                             cd /efficient-transformers && . preflight_qeff/bin/activate && mkdir -p /efficient-transformers/cli &&
                             export TOKENIZERS_PARALLELISM=false && export QEFF_ISOLATE_QAIC_WORKERS=1 && export QEFF_HOME=/efficient-transformers/cli &&
-                            python -m pytest tests/cloud/test_export_compile_execute.py -m '(cli and not qnn) and (not finetune) and ${CI_SELECTIVE_LAYER_FILTER}' -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=cli --junitxml=tests/tests_log3.xml --durations=10 &&
-                            junitparser merge tests/tests_log3.xml tests/tests_log.xml && deactivate"
+                            python -m pytest tests/cloud/test_export_compile_execute.py -m '(cli) and (not finetune) and ${CI_SELECTIVE_LAYER_FILTER}' -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=cli --junitxml=tests/tests_log3.xml --durations=10 &&
+                            deactivate"
                             '''
                         }
                     }
@@ -637,7 +639,7 @@ pipeline {
                             cd /efficient-transformers && . preflight_qeff/bin/activate && pip install -r examples/dynamo/causal_lm/requirements.txt &&
                             mkdir -p /efficient-transformers/dynamo_qeff_qaic && export TOKENIZERS_PARALLELISM=false && export QEFF_ISOLATE_QAIC_WORKERS=1 && export QEFF_HOME=/efficient-transformers/dynamo_qeff_qaic &&
                             python -m pytest tests/dynamo -m '(dynamo) and (on_qaic) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --ignore tests/dynamo/nightly -n ${CI_QAIC_WORKERS} -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=dynamo_qaic --junitxml=tests/tests_log_dynamo_qaic.xml --durations=10 &&
-                            junitparser merge tests/tests_log_dynamo_qaic.xml tests/tests_log.xml && deactivate"
+                            deactivate"
                             '''
                         }
                     }
@@ -656,7 +658,7 @@ pipeline {
                             mkdir -p /efficient-transformers/weight_free_qaic && export TOKENIZERS_PARALLELISM=false && export QEFF_ISOLATE_QAIC_WORKERS=1 && export QEFF_HOME=/efficient-transformers/weight_free_qaic &&
                             export HF_HUB_CACHE=/huggingface_hub && export HF_HUB_ENABLE_HF_TRANSFER=1 &&
                             python -m pytest tests/weight_free -m '(on_qaic) and ${IMPACT_TEST_FILTER} and ${CI_SELECTIVE_LAYER_FILTER}' --dist loadgroup -n ${WEIGHT_FREE_EXEC_N} -p scripts.ci_impact.pytest_plugin --impact-plan=.ci-impact-plan.json --impact-stage=weight_free_qaic --junitxml=tests/tests_log_weight_free_qaic.xml --durations=10 &&
-                            junitparser merge tests/tests_log_weight_free_qaic.xml tests/tests_log.xml && deactivate"
+                            deactivate"
                             '''
                         }
                     }
@@ -676,7 +678,7 @@ pipeline {
                             pip install torch==2.9.1 torchvision==0.24.1 torchaudio==2.9.1 --index-url https://download.pytorch.org/whl/cpu &&
                             mkdir -p /efficient-transformers/cli_qaic_finetuning && export TOKENIZERS_PARALLELISM=false && export QEFF_HOME=/efficient-transformers/cli_qaic_finetuning &&
                             pytest tests -m '(finetune)' --ignore tests/vllm --ignore tests/unit_test --ignore tests/nightly_pipeline --junitxml=tests/tests_log_finetune.xml --durations=10 &&
-                            junitparser merge tests/tests_log_finetune.xml tests/tests_log.xml && deactivate"
+                            deactivate"
                             '''
                         }
                     }
@@ -701,11 +703,8 @@ pipeline {
                         export QEFF_REPRODUCER_REPORT_MD=tests/reproducer_configs/reproducer_config_results.md &&
                         python -m pytest tests/reproducer_configs/test_reported_reproducer_configs.py -q -rs --junitxml=tests/tests_log_reproducer.xml --durations=10;
                         test_status=\\$?;
-                        junitparser merge tests/tests_log_reproducer.xml tests/tests_log.xml;
-                        merge_status=\\$?;
                         deactivate;
-                        if [ \"\\$test_status\" -ne 0 ]; then exit \"\\$test_status\"; fi;
-                        exit \"\\$merge_status\""
+                        if [ \"\\$test_status\" -ne 0 ]; then exit \"\\$test_status\"; fi"
                         '''
                     }
                 }
@@ -744,6 +743,17 @@ pipeline {
                         error("Refusing to remove unsafe qgenie tool path: ${env.CI_IMPACT_TRUSTED_TOOL_DIR}")
                     }
                     sh "sudo rm -rf '${env.CI_IMPACT_TRUSTED_TOOL_DIR}'"
+                }
+                try {
+                    sh '''
+                        sudo docker exec ${BUILD_TAG} bash -c "
+                        cd /efficient-transformers &&
+                        . preflight_qeff/bin/activate &&
+                        bash scripts/ci_report/merge_junit_results.sh &&
+                        deactivate"
+                    '''
+                } catch (error) {
+                    echo "Failed to merge JUnit results: ${error}"
                 }
                 try {
                     junit testResults: 'tests/tests_log.xml', allowEmptyResults: true
